keyconfig_data = \
[("Window",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'TOPBAR_MT_file_new'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'O', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'TOPBAR_MT_file_open_recent'),
       ],
      },
     ),
    ("wm.open_mainfile", {"type": 'O', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_mainfile", {"type": 'S', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_as_mainfile", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.quit_blender", {"type": 'Q', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'SCREEN_MT_user_menu'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F1', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'FILE_BROWSER'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F2', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'CLIP_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F3', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'NODE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F4', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'CONSOLE'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F5', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'VIEW_3D'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F6', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'GRAPH_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F7', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'PROPERTIES'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F8', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'SEQUENCE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F9', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'OUTLINER'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F10', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'IMAGE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F11', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'TEXT_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F12', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'DOPESHEET_EDITOR'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'NDOF_BUTTON_MENU', "value": 'PRESS'},
     {"properties":
      [("name", 'USERPREF_MT_ndof_settings'),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 1.1),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 0.90909094),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 1.5),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 0.6666667),
       ],
      },
     ),
    ("info.reports_display_update", {"type": 'TIMER_REPORT', "value": 'ANY', "any": True}, None),
    ("wm.doc_view_manual_ui_context", {"type": 'F1', "value": 'PRESS'}, None),
    ("wm.call_panel",
     {"type": 'F2', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_PT_name'),
       ("keep_open", False),
       ],
      },
     ),
    ("wm.search_menu", {"type": 'SPACE', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'F4', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_MT_file_context_menu'),
       ],
      },
     ),
    ("wm.toolbar", {"type": 'SPACE', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("Outliner",
  {"space_type": 'OUTLINER', "region_type": 'WINDOW'},
  {"items":
   [("outliner.highlight_update", {"type": 'MOUSEMOVE', "value": 'ANY', "any": True}, None),
    ("outliner.item_rename", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("extend", False),
       ("recursive", False),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("recursive", False),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("extend", False),
       ("recursive", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("recursive", True),
       ],
      },
     ),
    ("outliner.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("outliner.item_openclose",
     {"type": 'RET', "value": 'PRESS'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'RET', "value": 'PRESS', "shift": True},
     {"properties":
      [("all", True),
       ],
      },
     ),
    ("outliner.item_rename", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.operation", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("outliner.item_drag_drop", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("outliner.item_drag_drop", {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True}, None),
    ("outliner.show_hierarchy", {"type": 'HOME', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'PERIOD', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("outliner.scroll_page",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("up", False),
       ],
      },
     ),
    ("outliner.scroll_page",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("up", True),
       ],
      },
     ),
    ("outliner.show_one_level", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("outliner.show_one_level",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("open", False),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("outliner.expanded_toggle", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("outliner.keyingset_add_selected", {"type": 'K', "value": 'PRESS'}, None),
    ("outliner.keyingset_remove_selected", {"type": 'K', "value": 'PRESS', "alt": True}, None),
    ("anim.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("outliner.drivers_add_selected", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.drivers_delete_selected", {"type": 'D', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("outliner.collection_new", {"type": 'C', "value": 'PRESS'}, None),
    ("outliner.collection_delete", {"type": 'X', "value": 'PRESS'}, None),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("outliner.collection_exclude_set", {"type": 'E', "value": 'PRESS'}, None),
    ("outliner.collection_exclude_clear", {"type": 'E', "value": 'PRESS', "alt": True}, None),
    ("outliner.hide", {"type": 'H', "value": 'PRESS'}, None),
    ("outliner.unhide_all", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("outliner.id_copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.id_paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.collection_delete",
     {"type": 'BACK_SPACE', "value": 'PRESS'},
     {"properties":
      [("hierarchy", False),
       ],
      },
     ),
    ("outliner.object_operation",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("type", 'DELETE'),
       ],
      },
     ),
    ("outliner.collection_delete",
     {"type": 'BACK_SPACE', "value": 'PRESS', "shift": True},
     {"properties":
      [("hierarchy", True),
       ],
      },
     ),
    ("outliner.id_operation",
     {"type": 'DEL', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'DELETE'),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Paint Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_paint.brush.gpencil_settings.pen_strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_paint.brush.size'),
       ],
    "active":False,
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_draw_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_gpencil_draw_delete'),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Sculpt Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("gpencil.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_alternate", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_sculpt.brush.strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_sculpt.brush.size'),
       ],
    "active":False,
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_sculpt_context_menu'),
       ],
      },
     ),
    ("gpencil.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ],
   },
  ),
 ("Object Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("object.booltool_auto_slice", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.booltool_auto_intersect", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.booltool_auto_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.booltool_auto_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.to_mesh", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.brush_to_mesh", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_slice", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_inters", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_diff", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_booltool_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit_objects'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("object.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.select_linked", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("object.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("object.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("object.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("object.location_clear",
     {"type": 'G', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.rotation_clear",
     {"type": 'R', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.scale_clear",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ("confirm", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ("confirm", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_add'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_object_apply'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_make_links'),
       ],
      },
     ),
    ("object.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("object.duplicate_move_linked", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("object.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("anim.keyframe_insert_menu", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete_v3d", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("anim.keying_set_active_set", {"type": 'I', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.create", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("collection.objects_remove", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("collection.objects_remove_all", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.objects_add_active", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("collection.objects_remove_active", {"type": 'G', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_object_context_menu'),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("object.hide_view_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("object.hide_collection", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 1),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 2),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 3),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 4),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 5),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 6),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 7),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 8),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 9),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 10),
       ],
      },
     ),
    ("wm.tool_set_by_name", {"type": 'Q', "value": 'PRESS'}, None),
    ("wm.tool_set_by_name", {"type": 'Q', "value": 'PRESS', "shift": True}, None),
    ("wm.tool_set_by_name", {"type": 'W', "value": 'PRESS'}, None),
    ("wm.tool_set_by_name", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.tool_set_by_name", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("Curve",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_curve_add'),
       ],
      },
     ),
    ("curve.handle_type_set", {"type": 'V', "value": 'PRESS'}, None),
    ("curve.vertex_add", {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("curve.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("curve.select_row", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("curve.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("curve.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("curve.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("curve.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("curve.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("curve.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("curve.shortest_path_pick", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("curve.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("curve.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("curve.extrude_move", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("curve.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("curve.make_segment",
     {"type": 'F', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("curve.cyclic_toggle", {"type": 'C', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_delete'),
       ],
      },
     ),
    ("curve.dissolve_verts", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("curve.dissolve_verts", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("curve.tilt_clear", {"type": 'T', "value": 'PRESS', "alt": True}, None),
    ("transform.tilt", {"type": 'T', "value": 'PRESS', "ctrl": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'CURVE_SHRINKFATTEN'),
       ],
      },
     ),
    ("curve.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("curve.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("curve.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("curve.normals_make_consistent", {"type": 'N', "value": 'PRESS', "shift": True}, None),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ],
   },
  ),
 ("Image Paint",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("paint.image_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'NORMAL'),
       ],
      },
     ),
    ("paint.image_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("paint.brush_colors_flip", {"type": 'X', "value": 'PRESS'}, None),
    ("paint.grab_clone", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("paint.sample_color", {"type": 'S', "value": 'PRESS'}, None),
    ("brush.scale_size",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 0.9),
       ],
      },
     ),
    ("brush.scale_size",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 1.1111112),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.image_paint.brush.size'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.size'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_size'),
       ("rotation_path", 'tool_settings.image_paint.brush.mask_texture_slot.angle'),
       ("color_path", 'tool_settings.image_paint.brush.cursor_color_add'),
       ("fill_color_path", 'tool_settings.image_paint.brush.color'),
       ("fill_color_override_path", 'tool_settings.unified_paint_settings.color'),
       ("fill_color_override_test_path", 'tool_settings.unified_paint_settings.use_unified_color'),
       ("zoom_path", 'space_data.zoom'),
       ("image_id", 'tool_settings.image_paint.brush'),
       ("secondary_tex", True),
       ],
    "active":False,
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.image_paint.brush.strength'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.strength'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_strength'),
       ("rotation_path", 'tool_settings.image_paint.brush.mask_texture_slot.angle'),
       ("color_path", 'tool_settings.image_paint.brush.cursor_color_add'),
       ("fill_color_path", 'tool_settings.image_paint.brush.color'),
       ("fill_color_override_path", 'tool_settings.unified_paint_settings.color'),
       ("fill_color_override_test_path", 'tool_settings.unified_paint_settings.use_unified_color'),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.image_paint.brush'),
       ("secondary_tex", True),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path_primary", 'tool_settings.image_paint.brush.texture_slot.angle'),
       ("data_path_secondary", ''),
       ("use_secondary", ''),
       ("rotation_path", 'tool_settings.image_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.image_paint.brush.cursor_color_add'),
       ("fill_color_path", 'tool_settings.image_paint.brush.color'),
       ("fill_color_override_path", 'tool_settings.unified_paint_settings.color'),
       ("fill_color_override_test_path", 'tool_settings.unified_paint_settings.use_unified_color'),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.image_paint.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("data_path_primary", 'tool_settings.image_paint.brush.mask_texture_slot.angle'),
       ("data_path_secondary", ''),
       ("use_secondary", ''),
       ("rotation_path", 'tool_settings.image_paint.brush.mask_texture_slot.angle'),
       ("color_path", 'tool_settings.image_paint.brush.cursor_color_add'),
       ("fill_color_path", 'tool_settings.image_paint.brush.color'),
       ("fill_color_override_path", 'tool_settings.unified_paint_settings.color'),
       ("fill_color_override_test_path", 'tool_settings.unified_paint_settings.use_unified_color'),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.image_paint.brush'),
       ("secondary_tex", True),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'TRANSLATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SCALE'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ROTATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'TRANSLATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("mode", 'SCALE'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ROTATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("data_path", 'image_paint_object.data.use_paint_mask'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.image_paint.brush.use_smooth_stroke'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_angle_control'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.image_paint.brush.stroke_method'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_paint_texture_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Vertex Paint",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("paint.vertex_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'NORMAL'),
       ],
      },
     ),
    ("paint.vertex_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("paint.brush_colors_flip", {"type": 'X', "value": 'PRESS'}, None),
    ("paint.sample_color", {"type": 'S', "value": 'PRESS'}, None),
    ("paint.vertex_color_set", {"type": 'K', "value": 'PRESS', "shift": True}, None),
    ("brush.scale_size",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 0.9),
       ],
      },
     ),
    ("brush.scale_size",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 1.1111112),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.vertex_paint.brush.size'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.size'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_size'),
       ("rotation_path", 'tool_settings.vertex_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.vertex_paint.brush.cursor_color_add'),
       ("fill_color_path", 'tool_settings.vertex_paint.brush.color'),
       ("fill_color_override_path", 'tool_settings.unified_paint_settings.color'),
       ("fill_color_override_test_path", 'tool_settings.unified_paint_settings.use_unified_color'),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.vertex_paint.brush'),
       ("secondary_tex", False),
       ],
    "active":False,
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.vertex_paint.brush.strength'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.strength'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_strength'),
       ("rotation_path", 'tool_settings.vertex_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.vertex_paint.brush.cursor_color_add'),
       ("fill_color_path", 'tool_settings.vertex_paint.brush.color'),
       ("fill_color_override_path", 'tool_settings.unified_paint_settings.color'),
       ("fill_color_override_test_path", 'tool_settings.unified_paint_settings.use_unified_color'),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.vertex_paint.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path_primary", 'tool_settings.vertex_paint.brush.texture_slot.angle'),
       ("data_path_secondary", ''),
       ("use_secondary", ''),
       ("rotation_path", 'tool_settings.vertex_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.vertex_paint.brush.cursor_color_add'),
       ("fill_color_path", 'tool_settings.vertex_paint.brush.color'),
       ("fill_color_override_path", 'tool_settings.unified_paint_settings.color'),
       ("fill_color_override_test_path", 'tool_settings.unified_paint_settings.use_unified_color'),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.vertex_paint.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'TRANSLATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SCALE'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ROTATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'TRANSLATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("mode", 'SCALE'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ROTATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("data_path", 'vertex_paint_object.data.use_paint_mask'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.vertex_paint.brush.use_smooth_stroke'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_angle_control'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.vertex_paint.brush.stroke_method'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_paint_vertex_context_menu'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("data_path", 'vertex_paint_object.data.use_paint_mask_vertex'),
       ],
      },
     ),
    ],
   },
  ),
 ("Weight Paint",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("paint.weight_paint", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("paint.weight_sample", {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("paint.weight_sample_group", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("paint.weight_gradient",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("type", 'LINEAR'),
       ],
      },
     ),
    ("paint.weight_gradient",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("type", 'RADIAL'),
       ],
      },
     ),
    ("paint.weight_set", {"type": 'K', "value": 'PRESS', "shift": True}, None),
    ("brush.scale_size",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 0.9),
       ],
      },
     ),
    ("brush.scale_size",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 1.1111112),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.weight_paint.brush.size'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.size'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_size'),
       ("rotation_path", 'tool_settings.weight_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.weight_paint.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.weight_paint.brush'),
       ("secondary_tex", False),
       ],
    "active":False,
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.weight_paint.brush.strength'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.strength'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_strength'),
       ("rotation_path", 'tool_settings.weight_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.weight_paint.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.weight_paint.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path_primary", 'tool_settings.weight_paint.brush.weight'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.weight'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_weight'),
       ("rotation_path", 'tool_settings.weight_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.weight_paint.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.weight_paint.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.vertex_paint.brush.stroke_method'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("data_path", 'weight_paint_object.data.use_paint_mask'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("data_path", 'weight_paint_object.data.use_paint_mask_vertex'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.weight_paint.brush.use_smooth_stroke'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_paint_weight_context_menu'),
       ],
      },
     ),
    ("view3d.select", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ("Sculpt",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'NORMAL'),
       ],
      },
     ),
    ("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SMOOTH'),
       ],
      },
     ),
    ("paint.hide_show",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("action", 'SHOW'),
       ("area", 'INSIDE'),
       ],
      },
     ),
    ("paint.hide_show",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("action", 'HIDE'),
       ("area", 'INSIDE'),
       ],
      },
     ),
    ("paint.hide_show",
     {"type": 'H', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'SHOW'),
       ("area", 'ALL'),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("level", 1),
       ("relative", True),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("level", -1),
       ("relative", True),
       ],
      },
     ),
    ("paint.mask_flood_fill",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'VALUE'),
       ("value", 0.0),
       ],
      },
     ),
    ("paint.mask_flood_fill",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("paint.mask_lasso_gesture", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'M', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'scene.tool_settings.sculpt.show_mask'),
       ],
      },
     ),
    ("sculpt.dynamic_topology_toggle", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("sculpt.set_detail_size", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("brush.scale_size",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 0.9),
       ],
      },
     ),
    ("brush.scale_size",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 1.1111112),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.size'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.size'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_size'),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
    "active":False,
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.strength'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.strength'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_strength'),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("data_path_secondary", ''),
       ("use_secondary", ''),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'TRANSLATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SCALE'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ROTATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'TRANSLATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("mode", 'SCALE'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ROTATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'DRAW'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'SMOOTH'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'P', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'PINCH'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'I', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'INFLATE'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'GRAB'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'LAYER'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("sculpt_tool", 'FLATTEN'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'C', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'CLAY'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("sculpt_tool", 'CREASE'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'SNAKE_HOOK'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'MASK'),
       ("toggle", True),
       ("create_missing", True),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.sculpt.brush.stroke_method'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.sculpt.brush.use_smooth_stroke'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_angle_control'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_sculpt_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Mesh",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("mesh.loopcut_slide",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.offset_edge_loops_slide",
     {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.inset", {"type": 'I', "value": 'PRESS'}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("vertex_only", False),
       ],
      },
     ),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("vertex_only", True),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mesh.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_similar'),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mesh.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True},
     {"properties":
      [("inside", False),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("view3d.edit_mesh_extrude_move_normal", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_extrude'),
       ],
      },
     ),
    ("transform.edge_crease", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("mesh.fill", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.tris_convert_to_quads", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", True),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_edge_move", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_merge'),
       ],
      },
     ),
    ("transform.shrink_fatten", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("mesh.edge_face_add",
     {"type": 'F', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("mesh.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_mesh_add'),
       ],
      },
     ),
    ("mesh.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("mesh.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("mesh.vert_connect_path", {"type": 'J', "value": 'PRESS'}, None),
    ("mesh.point_normals", {"type": 'L', "value": 'PRESS', "alt": True}, None),
    ("transform.vert_slide", {"type": 'V', "value": 'PRESS', "shift": True}, None),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("use_occlude_geometry", True),
       ("only_selected", False),
       ],
      },
     ),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_faces'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_edges'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_vertices'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_uv_map'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_vertex_group'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_normals'),
       ],
      },
     ),
    ("object.vertex_group_remove_from", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.tool_set_by_name", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("wm.tool_set_by_name", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("wm.tool_set_by_name", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("wm.tool_set_by_name", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("wm.tool_set_by_name", {"type": 'R', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.tool_set_by_name", {"type": 'Q', "value": 'PRESS'}, None),
    ("wm.tool_set_by_name", {"type": 'Q', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("Armature",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("armature.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("armature.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("armature.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("armature.align", {"type": 'A', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("armature.calculate_roll", {"type": 'N', "value": 'PRESS', "shift": True}, None),
    ("armature.roll_clear", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("armature.switch_direction", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("armature.bone_primitive_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("armature.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("armature.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("armature.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("armature.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("armature.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("armature.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("armature.select_mirror",
     {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("armature.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("armature.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("armature.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("armature.select_linked",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("armature.select_linked",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("armature.shortest_path_pick", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_armature_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_armature_delete'),
       ],
      },
     ),
    ("armature.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("armature.dissolve", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("armature.dissolve", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("armature.extrude_move", {"type": 'E', "value": 'PRESS'}, None),
    ("armature.extrude_forked", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("armature.click_extrude", {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("armature.fill",
     {"type": 'F', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("armature.merge", {"type": 'M', "value": 'PRESS', "alt": True}, None),
    ("armature.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("armature.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_toggle'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_enable'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_disable'),
       ],
      },
     ),
    ("armature.layers_show_all", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("armature.armature_layers", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("armature.bone_layers", {"type": 'M', "value": 'PRESS'}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'BONE_SIZE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'BONE_ENVELOPE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'BONE_ROLL'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_armature_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Particle",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("particle.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("particle.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("particle.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("particle.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("particle.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("particle.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("particle.select_linked",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("particle.select_linked",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("particle.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("particle.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("particle.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("particle.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("particle.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("particle.brush_edit", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("particle.brush_edit", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.particle_edit.brush.size'),
       ],
    "active":False,
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.particle_edit.brush.strength'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_particle_context_menu'),
       ],
      },
     ),
    ("particle.weight_set", {"type": 'K', "value": 'PRESS', "shift": True}, None),
    ("wm.context_set_enum",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.particle_edit.select_mode'),
       ("value", 'PATH'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.particle_edit.select_mode'),
       ("value", 'POINT'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.particle_edit.select_mode'),
       ("value", 'TIP'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Weight Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.sculpt_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ("gpencil.sculpt_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_sculpt.weight_brush.strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_sculpt.weight_brush.size'),
       ],
    "active":False,
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ],
   },
  ),
 ("View3D Fly Modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CANCEL", {"type": 'RIGHTMOUSE', "value": 'ANY', "any": True}, None),
    ("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'LEFTMOUSE', "value": 'ANY', "any": True}, None),
    ("CONFIRM", {"type": 'RET', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'SPACE', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "any": True}, None),
    ("ACCELERATE", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "any": True}, None),
    ("DECELERATE", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "any": True}, None),
    ("ACCELERATE", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "any": True}, None),
    ("DECELERATE", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("PAN_ENABLE", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "any": True}, None),
    ("PAN_DISABLE", {"type": 'MIDDLEMOUSE', "value": 'RELEASE', "any": True}, None),
    ("FORWARD", {"type": 'W', "value": 'PRESS'}, None),
    ("BACKWARD", {"type": 'S', "value": 'PRESS'}, None),
    ("LEFT", {"type": 'A', "value": 'PRESS'}, None),
    ("RIGHT", {"type": 'D', "value": 'PRESS'}, None),
    ("UP", {"type": 'E', "value": 'PRESS'}, None),
    ("DOWN", {"type": 'Q', "value": 'PRESS'}, None),
    ("UP", {"type": 'R', "value": 'PRESS'}, None),
    ("DOWN",
     {"type": 'F', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("FORWARD", {"type": 'UP_ARROW', "value": 'PRESS'}, None),
    ("BACKWARD", {"type": 'DOWN_ARROW', "value": 'PRESS'}, None),
    ("LEFT", {"type": 'LEFT_ARROW', "value": 'PRESS'}, None),
    ("RIGHT", {"type": 'RIGHT_ARROW', "value": 'PRESS'}, None),
    ("AXIS_LOCK_X", {"type": 'X', "value": 'PRESS'}, None),
    ("AXIS_LOCK_Z", {"type": 'Z', "value": 'PRESS'}, None),
    ("PRECISION_ENABLE", {"type": 'LEFT_ALT', "value": 'PRESS', "any": True}, None),
    ("PRECISION_DISABLE", {"type": 'LEFT_ALT', "value": 'RELEASE', "any": True}, None),
    ("PRECISION_ENABLE", {"type": 'LEFT_SHIFT', "value": 'PRESS', "any": True}, None),
    ("PRECISION_DISABLE", {"type": 'LEFT_SHIFT', "value": 'RELEASE', "any": True}, None),
    ("FREELOOK_ENABLE", {"type": 'LEFT_CTRL', "value": 'PRESS', "any": True}, None),
    ("FREELOOK_DISABLE", {"type": 'LEFT_CTRL', "value": 'RELEASE', "any": True}, None),
    ],
   },
  ),
 ("Node Generic",
  {"space_type": 'NODE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("wm.context_toggle",
     {"type": 'T', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.show_region_toolbar'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'N', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.show_region_ui'),
       ],
      },
     ),
    ("node.add_search",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("use_transform", True),
       ],
      },
     ),
    ],
   },
  ),
 ("File Browser Main",
  {"space_type": 'FILE_BROWSER', "region_type": 'WINDOW'},
  {"items":
   [("file.execute",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("need_active", True),
       ],
      },
     ),
    ("file.refresh", {"type": 'F', "value": 'PRESS'}, None),
    ("file.select", {"type": 'LEFTMOUSE', "value": 'CLICK'}, None),
    ("file.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("file.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select",
     {"type": 'RIGHTMOUSE', "value": 'CLICK'},
     {"properties":
      [("open", False),
       ],
      },
     ),
    ("file.select",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("open", False),
       ],
      },
     ),
    ("file.select",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("extend", True),
       ("fill", True),
       ("open", False),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS'},
     {"properties":
      [("direction", 'UP'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS'},
     {"properties":
      [("direction", 'DOWN'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS'},
     {"properties":
      [("direction", 'LEFT'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'LEFT'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'LEFT'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS'},
     {"properties":
      [("direction", 'RIGHT'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.previous", {"type": 'BUTTON4MOUSE', "value": 'CLICK'}, None),
    ("file.next", {"type": 'BUTTON5MOUSE', "value": 'CLICK'}, None),
    ("file.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("file.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("file.select_box", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("file.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("file.rename", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("file.highlight", {"type": 'MOUSEMOVE', "value": 'ANY', "any": True}, None),
    ("file.filenum",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS'},
     {"properties":
      [("increment", 1),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("increment", 10),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("increment", 100),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("increment", -1),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("increment", -10),
       ],
      },
     ),
    ("file.filenum",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("increment", -100),
       ],
      },
     ),
    ],
   },
  ),
 ("Clip Editor",
  {"space_type": 'CLIP_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("clip.view_pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("clip.view_pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("clip.view_pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("clip.view_zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("clip.view_zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("clip.view_zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("clip.view_zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("clip.view_zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("clip.view_zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("clip.view_zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS'}, None),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("ratio", 1.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.5),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.25),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.125),
       ],
      },
     ),
    ("clip.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("clip.view_all",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("fit_view", True),
       ],
    "active":False,
      },
     ),
    ("clip.view_selected", {"type": 'F', "value": 'PRESS'}, None),
    ("clip.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("clip.view_ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("clip.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("position", 'PATHSTART'),
       ],
      },
     ),
    ("clip.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("position", 'PATHEND'),
       ],
      },
     ),
    ("clip.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("position", 'FAILEDPREV'),
       ],
      },
     ),
    ("clip.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("position", 'PATHSTART'),
       ],
      },
     ),
    ("clip.change_frame", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("clip.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ("deselect_all", True),
       ],
      },
     ),
    ("clip.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("clip.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("clip.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("clip.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("clip.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("clip.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("clip.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'CLIP_MT_select_grouped'),
       ],
      },
     ),
    ("clip.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("clip.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("clip.add_marker_slide", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("clip.delete_marker", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("clip.delete_marker", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("clip.slide_marker", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("clip.disable_markers",
     {"type": 'D', "value": 'PRESS', "shift": True},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("clip.delete_track", {"type": 'X', "value": 'PRESS'}, None),
    ("clip.delete_track", {"type": 'DEL', "value": 'PRESS'}, None),
    ("clip.lock_tracks",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'LOCK'),
       ],
      },
     ),
    ("clip.lock_tracks",
     {"type": 'L', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'UNLOCK'),
       ],
      },
     ),
    ("clip.hide_tracks",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("clip.hide_tracks",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("clip.hide_tracks_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("clip.slide_plane_marker", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("clip.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("clip.keyframe_delete", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("clip.join_tracks", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'CLIP_MT_tracking_context_menu'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.lock_selection'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'D', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'space_data.show_disabled'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'space_data.show_marker_search'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.use_mute_footage'),
       ],
      },
     ),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("clip.clear_track_path",
     {"type": 'T', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'REMAINED'),
       ("clear_active", False),
       ],
      },
     ),
    ("clip.clear_track_path",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("action", 'UPTO'),
       ("clear_active", False),
       ],
      },
     ),
    ("clip.clear_track_path",
     {"type": 'T', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("action", 'ALL'),
       ("clear_active", False),
       ],
      },
     ),
    ("clip.cursor_set", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'CLIP_MT_pivot_pie'),
       ],
      },
     ),
    ("clip.copy_tracks", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("clip.paste_tracks", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(os.path.splitext(os.path.basename(__file__))[0], keyconfig_data)
